spring.application.name=PhoneBook_Starter_Java_SpringBoot

# Database configuration for SQLite
spring.datasource.url=jdbc:sqlite:phonebook.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA configuration
# Use the Hibernate Community SQLite dialect:
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable Open-In-View for performance
spring.jpa.open-in-view=false

# Logging (optional, for debugging)
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.filter=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
